apiVersion: v1
kind: ServiceAccount
metadata:
  name: oo-k8s
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oo-k8s
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
    resources: ["pods","deployments","replicasets"]
    verbs: ["get", "watch", "list", "update", "create", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oo-k8s
  namespace: default
roleRef:
  kind: Role
  name: oo-k8s
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: oo-k8s
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: oo-k8s
spec:
  serviceAccount: oo-k8s
  containers:
  - name: oo-k8s
    image: oo-k8s
    imagePullPolicy: Never # for minikube
